name: Trigger auto deployment for api-python

on:
  workflow_dispatch:

jobs:
  note:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This portal-generated workflow was causing conflicts."
          echo "Use the two workflows instead:"
          echo " - build-api-python-to-acr"
          echo " - Build & Deploy Python API to Azure Container Apps"
