name: build-and-push

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: api
            context: ./api-dotnet
            file: ./api-dotnet/Dockerfile
            image_suffix: -api

          - name: background
            context: .
            file: ./src/JobPortal.Background/Dockerfile
            image_suffix: -bg

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}${{ matrix.image_suffix }}:latest
            ghcr.io/${{ github.repository }}${{ matrix.image_suffix }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
